routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/test', function () {
//    dd(\Tshevchenko\Rbac\Services\ActionService::getActions());
})/*->middleware([Rbac::class])*/;

Auth::routes();

Route::middleware(['auth', 'rbac'])->prefix('/admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('/user', UserController::class);
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('/profile')->group(function () {
        Route::get('/', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/', [ProfileController::class, 'update'])->name('profile.update');
        Route::delete('/', [ProfileController::class, 'destroy'])->name('profile.destroy');
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Tshevchenko\CustomFields\Models\Traits\CustomFieldsTrait;
use Tshevchenko\Rbac\Models\Traits\RbacTrait;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasApiTokens, RbacTrait, SoftDeletes, CustomFieldsTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'lastname',
        'email',
        'phone',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    public function getFullNameAttribute(): string
    {
        return $this->name . ' ' . $this->lastname;
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Support\Renderable;

class DashboardController extends Controller
{
    /**
     * Show the admin panel dashboard.
     *
     * @return Renderable
     */
    public function index(): Renderable
    {
        return view('admin.dashboard');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Models\User;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Hash;
use Tshevchenko\Rbac\Models\RbacRole;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index(): Renderable
    {
        return view('admin.user.index', [
            'users' => User::with('roles')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create(): Renderable
    {
        return view('admin.user.create', [
            'roles' => RbacRole::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserRequest $request
     * @return RedirectResponse
     */
    public function store(UserRequest $request): RedirectResponse
    {
        try {
            $data = $request->validated();
            $data['password'] = Hash::make($request['password']);

            $user = User::create($data);

            $user->roles()->sync($data['roles']);
        } catch (\Exception $e) {
            return redirect()
                ->route('admin.user.create')
                ->withErrors([$e->getMessage()]);
        }

        return redirect()->route('admin.user.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Renderable
     */
    public function edit(User $user): Renderable
    {
        $user->load('roles');

        return view('admin.user.edit', [
            'roles' => RbacRole::all(),
            'user' => $user,
            'activeRolesID' => $user->roles->pluck('id')->toArray(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UserRequest $request, User $user): RedirectResponse
    {
        try {
            $data = $request->validated();

            if (!empty($data['password'])) {
                $data['password'] = Hash::make($data['password']);
            } else {
                unset($data['password']);
            }

            $user->update($data);

            $user->roles()->sync($data['roles'] ?? []);

            return redirect()
                ->route('admin.user.edit', $user)
                ->with('success', trans('common.update_successful'));
        } catch (\Exception $e) {
            return redirect()
                ->route('admin.user.edit', $user)
                ->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->route('admin.user.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileRequest;
use App\Models\User;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\RedirectResponse;
use \DB;
use \Hash;
use \Auth;

class ProfileController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     *
     * @return Renderable
     */
    public function edit(): Renderable
    {
        $user = Auth::user();

        $user->load('roles', 'customFields');
        $f = $user->custom_fields;

        return view('profile.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProfileRequest $request
     * @return RedirectResponse
     */
    public function update(ProfileRequest $request): RedirectResponse
    {
        try {
            $data = $request->validated();

            if (!empty($data['password'])) {
                $data['password'] = Hash::make($data['password']);
            } else {
                unset($data['password']);
            }

            $user = User::findOrFail(Auth::id());

            DB::beginTransaction();

            $user->update($data);

            if (!empty($data['custom_fields'])) {
                array_walk(
                    $data['custom_fields'],
                    fn ($v, $k) => $user->customFields()->updateOrCreate(
                        ['key' => $k],
                        ['value' => $v, 'field_type' => '_test']
                    ),
                );
            }

            DB::commit();

            return redirect()
                ->route('profile.edit')
                ->with('success', trans('common.update_successful'));
        } catch (\Exception $e) {
            DB::rollback();

            return redirect()
                ->route('profile.edit')
                ->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return RedirectResponse
     */
    public function destroy(): RedirectResponse
    {
        Auth::user()->delete();

        Auth::logout();

        return redirect('/');
    }
}

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto mb-3">
                @include('admin.user.particles.form-header', [
                    'title' => __('admin/user.create_title'),
                ])
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 mx-auto">
                <form class="form-horizontal" action="{{ route('admin.user.store') }}" method="post">
                    {{ csrf_field() }}

                    @include('admin.user.particles.form')

                    <hr/>

                    <a href="{{ route('admin.user.index') }}" class="btn btn-default">
                        {{ trans('admin/common.cancel') }}
                    </a>

                    <input type="submit" class="btn btn-primary" value="{{ trans('admin/common.save') }}">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto mb-5">
                @include('admin.user.particles.form-header', [
                    'title' => __('admin/user.edit_title'),
                ])
            </div>
        </div>

        <form class="form-horizontal" action="{{ route('admin.user.update', $user) }}" method="post">
            {{ method_field('PUT') }}

            {{csrf_field()}}

            @include('admin.user.particles.form', [
                'user' => $user,
            ])

            <hr/>

            <a href="{{ route('admin.user.index') }}" class="btn btn-default">
                {{ trans('admin/common.cancel') }}
            </a>

            <input type="submit" class="btn btn-primary" value="{{ trans('admin/common.save') }}">

        </form>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header">{{ __('admin/user.index_title') }}</div>

                <div class="card-body">
                    <a href="{{ route('admin.user.create') }}" class="btn btn-primary">
                        {{ __('admin/common.create') }}
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 mx-auto">
            @if($users->count())
                <table class="mt-5 table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Username</th>
                            <th scope="col">E-Mail</th>
                            <th scope="col" width="100"></th>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>
                                <a href="{{ route('admin.user.edit', $user->id) }}">
                                    {{ $user->full_name }}
                                </a>
                            </td>

                            <td>
                                <a href="{{ route('admin.user.edit', $user->id) }}">
                                    {{ $user->email }}
                                </a>
                            </td>

                            <td class="action">
                                <a
                                    href="{{ route('admin.user.edit', $user->id) }}"
                                    class="btn btn-sm btn-outline-primary"
                                >
                                    <i class="fa-solid fa-user-pen"></i>
                                </a>

                                <form
                                    onsubmit="return confirm('Delete?')"
                                    action="{{ route('admin.user.destroy', $user) }}"
                                    method="post"
                                    class="d-inline-block"
                                >
                                    @csrf
                                    @method('DELETE')
                                    <button
                                        class="btn btn-sm btn-outline-danger"
                                        type="submit"
                                        title="{{ trans('admin/common.delete') }}"
                                    >
                                        <i class="fa-regular fa-trash-can"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/particles/form-header.blade.php
<div class="card">
    <div class="card-header border-0">
        <a href="{{ route('admin.user.index') }}" class="btn btn-sm btn-outline-warning me-1">
            <i class="fa-solid fa-chevron-left"></i>
        </a>

        {{ $title ?? '' }}
    </div>
</div>

resources/views/admin/user/particles/form.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="row">
    <div class="col-lg-8">
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.name') }} *</label>

                <input
                    type="text"
                    class="form-control"
                    name="name"
                    placeholder="{{ trans('admin/user.name') }}"
                    value="{{ old('name', !empty($user) ? $user->name : "") }}"
                />
            </div>

            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.lastname') }}</label>

                <input
                    type="text"
                    class="form-control"
                    name="lastname"
                    placeholder="{{ trans('admin/user.lastname') }}"
                    value="{{ old('lastname', !empty($user) ? $user->lastname : '') }}"
                />
            </div>

            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.email') }} *</label>

                <input
                    type="email"
                    class="form-control"
                    name="email"
                    placeholder="{{ trans('admin/user.email') }}"
                    value="{{ old('email', !empty($user) ? $user->email : "") }}"
                />
            </div>

            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.phone') }} *</label>

                <input
                    type="tel"
                    class="form-control"
                    name="phone"
                    placeholder="{{ trans('admin/user.phone') }}"
                    value="{{ old('phone', !empty($user) ? $user->phone : "") }}"
                />
            </div>

            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.password') }}</label>

                <input type="password" class="form-control" name="password">
            </div>

            <div class="col-md-6 mb-3">
                <label for="">{{ trans('admin/user.password_confirm') }}</label>

                <input type="password" class="form-control" name="password_confirmation">
            </div>
        </div>
    </div>

    @if($roles)
        <div class="col-lg-4">
            <label class="form-label">{{ __('admin/common.label_roles') }}</label>

            @foreach($roles as $role)
                <label class="form-check">
                    <input
                        class="form-check-input"
                        type="checkbox"
                        value="{{ $role->id }}"
                        name="roles[]"
                        {{ !empty($activeRolesID) && in_array($role->id, $activeRolesID) ? 'checked' : '' }}
                    />

                    {{ $role->title }}
                </label>
            @endforeach
        </div>
    @endif
</div>

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <link href="/assets/fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="/assets/fontawesome/css/brands.css" rel="stylesheet">
    <link href="/assets/fontawesome/css/solid.css" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app" class="platform-layout">
        <header class="platform-layout__header">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Platform') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav me-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ms-auto">
                            <!-- Authentication Links -->
                            @guest
                                @if (Route::has('login'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                    </li>
                                @endif

                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('profile.edit') }}">
                                            {{ __('Profile') }}
                                        </a>

                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="platform-layout__wrapper">
            <aside class="platform-layout__sidebar">
                @include('layouts.particles.admin-sidebar-menu')
            </aside>

            <main class="platform-layout__content">
                @yield('content')
            </main>
        </div>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <link href="/assets/fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="/assets/fontawesome/css/brands.css" rel="stylesheet">
    <link href="/assets/fontawesome/css/solid.css" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app" class="platform-layout">
        <header class="platform-layout__header">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Platform') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav me-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ms-auto">
                            <!-- Authentication Links -->
                            @guest
                                @if (Route::has('login'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                    </li>
                                @endif

                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="platform-layout__wrapper">

            <main class="platform-layout__content">
                @yield('content')
            </main>
        </div>
    </div>
</body>
</html>

resources/views/layouts/particles/admin-sidebar-menu.blade.php
<nav class="sidebar-menu">
    <ul class="sidebar-menu__list">
        @if(\Auth::user()->hasAccess('admin.dashboard'))
            <li class="sidebar-menu-item">
                <a href="{{ route('admin.dashboard') }}" class="sidebar-menu-item__link">
                    <span class="sidebar-menu-item__icon">
                        <i class="fa-solid fa-house"></i>
                    </span>

                    <span class="sidebar-menu-item__text">
                        {{ __('Dashboard') }}
                    </span>
                </a>
            </li>
        @endif
    </ul>

    <ul class="sidebar-menu__list">
        @if(\Auth::user()->hasAccess('admin.user.index'))
            <li class="sidebar-menu-item">
                <a href="{{ route('admin.user.index') }}" class="sidebar-menu-item__link">
                    <span class="sidebar-menu-item__icon">
                        <i class="fa-solid fa-user"></i>
                    </span>

                    <span class="sidebar-menu-item__text">
                        {{ __('Users') }}
                    </span>
                </a>
            </li>
        @endif

        @if(\Auth::user()->hasAccess(config('rbac.route_name') . 'role.index'))
            <li class="sidebar-menu-item">
                <a href="{{ route(config('rbac.route_name') . 'role.index') }}" class="sidebar-menu-item__link">
                    <span class="sidebar-menu-item__icon">
                        <i class="fa-solid fa-users"></i>
                    </span>

                    <span class="sidebar-menu-item__text">
                        {{ __('Roles') }}
                    </span>
                </a>
            </li>
        @endif

        @if(\Auth::user()->hasAccess(config('rbac.route_name') . 'action.index'))
            <li class="sidebar-menu-item">
                <a href="{{ route(config('rbac.route_name') . 'action.index') }}" class="sidebar-menu-item__link">
                    <span class="sidebar-menu-item__icon">
                        <i class="fa-solid fa-handshake"></i>
                    </span>

                    <span class="sidebar-menu-item__text">
                        {{ __('Permissions') }}
                    </span>
                </a>
            </li>
        @endif
    </ul>
</nav>